# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40ffa0474925cedd27d53840ca8b6024b1adb2847d0d465b6fa41793017bdba86ab73e679f657faf434f86460d9057aac582f1bdedea1a746858d7f131bf8ebc

test:
  secret_key_base: 2b6a82a91d9014dc7b7997174aa1a64a302648fa850740546b788e4ce5cfc474152993d51f22c60bdd8f686c10e3e656e8b3e04d6f5478e367f5603d97597692

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
